name: wasm-info

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v1
      - name: Cache Node Template
        uses: actions/cache@v1
        env:
          cache-name: substrate-cache
        with:
          path: ./target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*/Cargo.lock') }}
      - name: Build
        run: cargo build -vv --release
      - name: Run tests
        run: cargo test -vv --release
